NumPy

In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5]) ,([6,7,8,9,10])

print(arr)
print(type(arr))

(array([1, 2, 3, 4, 5]), [6, 7, 8, 9, 10])
<class 'tuple'>


Dimensions

In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


2D

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
print('Element at [0,0]: ', arr[0,0])
print('Element at [0,1]: ', arr[0,1])
print('Element at [0,2]: ', arr[0,2])
print('Element at [1,0]: ', arr[1,0])
print('Element at [1,1]: ', arr[1,1])
print('Element at [1,2]: ', arr[1,2])

Element at [0,0]:  1
Element at [0,1]:  2
Element at [0,2]:  3
Element at [1,0]:  6
Element at [1,1]:  7
Element at [1,2]:  8


copy

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


View

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

arr = np.array([[[0,1],[0,2],[0,3]]])

for x in arr:
  for y in x:
    print(y)

[0 1]
[0 2]
[0 3]


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]]])

for x in arr:
  print(x)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy
a.np array([[1,2,3],[2,3,5]])


SyntaxError: invalid syntax (2175469032.py, line 2)